# This is a basic workflow to help you get started with Actions

name: Automation

# Controls when the workflow will run
on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  add_to_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Assign to One Project
      # You may pin to the exact commit or the version.
      # uses: srggrs/assign-one-project-github-action@65a8ddab497df42ef268001e67bbf976f8fd39e1
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        # The url of the project to be assigned to.
        project: https://github.com/onflow/developer-grants/projects/1
        # The column name of the project, defaults to "To do" for issues and "In progress" for pull requests.
        column_name: "New: In review"

